-- require("flow").setup {
--   dark_theme = true,        -- Set the theme with dark background.
--   high_contrast = false,    -- Make the dark background darker or the light background lighter.
--   transparent = false,      -- Set transparent background.
--   fluo_color = "pink",      -- Color used as fluo. Available values are pink, yellow, orange, or green.
--   aggressive_spell = false, -- Use colors for spell check.
--   mode = "dark",            -- Mode of the colors. Available values are: dark, bright, desaturate, or base.
--
--   config = function()
--     vim.cmd('colorscheme flow')
--   end
-- }
