#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/ ~/projects ~/projects/mlops/ ~/projects/gpt/ ~/projects/automation/ ~/projects/temp/ ~/projects/consulting/ ~/projects/network/ ~/projects/lakehouse/ -not -path '*/.*' -type d -o -type l -maxdepth 1| fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    exit 0
fi

# if ! tmux has-session -t=$selected_name 2> /dev/null; then
tmux new-window -n $selected_name -c $selected
# fi

# tmux switch-client -t $selected_name
